// export const locale = {
//     lang: 'en',
//     data: {
//         'NAV': {
//             'UPLOAD_FAILED': 'Upload file failed!',
//             'APPLICATIONS': 'Applications',
//             'APPLICATION.1': 'APPLICATION',
//             'APPLICATION.1.1': 'User',
//             'CUSTOMER.1.1': 'List',
//             'CUSTOMER.1.2': 'Create',
//             'APPLICATION.1.2': 'Store/Department',
//             'COMPANY.1.1': 'List',
//             'COMPANY.1.2': 'Create',
//             'APPLICATION.1.3': 'Potential Store',
//             'LEAD.1.1': 'List',
//             'LEAD.1.2': 'Create',
//             'BU.1.1': 'List',
//             'BU.1.2': 'Create',
//             'APPLICATION.1.70': 'Unit',
//             'APPLICATION.1.4': 'Contract',
//             'CONTRACT.1.1': 'List',
//             'APPLICATION.1.7': 'Employee',
//             'HR_EMPLOYEE.1.1': 'List',
//             'APPLICATION.1.9': 'Frequently Asked Questions (FAQ)',
//             'FAQ.1.1': 'List',
//             'APPLICATION.1.6': 'Ticket',
//             'APPLICATION.1.11': 'Building',
//             'PLACE.1.1': 'List',
//             'SUPPORTER_TICKET.1.1': 'List',
//             'SUPPORTER_TICKET.1.2': 'Ticket to Follow',
//             'APPLICATION.1.10': 'SLA Management',
//             'SLA.1.1': 'List',
//             'APPLICATION.1.5': 'My Task',
//             'MY_TASK.1.1': 'List',
//             'APPLICATION.1.8': 'System',
//             'USER_JOB.1.1': 'Processing List',
//             'APPLICATION.2': 'Report',
//             'APPLICATION.2.2': 'Thống kê yêu cầu',
//             'APPLICATION.2.3': 'Call center',
//             'ANALYTICS.1.3': 'Application',
//             'ANALYTICS.1.1': 'Business Unit',
//             'ACCEPTANCE.1.1': 'Volume',
//             'ACCEPTANCE.1.2': 'Reconcile',
//             'DASHBOARD.1.1': 'Dashboard',
//             'DASHBOARD_ADMIN.1.1': 'Dashboard admin',
//             'REPORT_TICKET.1.2': 'Theo trạng thái',
//             'REPORT_TICKET.1.1': 'Theo thời gian',
//             'REPORT_TICKET.1.3': 'Theo nguồn khách hàng',
//             'REPORT_TICKET.1.4': 'Theo tòa nhà',
//             'REPORT_TICKET.1.5': 'Theo dịch vụ',
//             'REPORT_TICKET.1.6': 'Theo thời lượng xử lý',
//             'REPORT_TICKET.1.7': 'Trùng nội dung',
//             'REPORT_TICKET.1.8': 'Theo SLA',
//             'REPORT_CALL.1.1': 'Theo số lượng',
//             'REPORT_CALL.1.2': 'Theo thời lượng',
//             'APPLICATION.2.1': 'Acceptance',
//             'REPORT_CALL_AGG.1.1': 'Báo cáo tổng hợp',
//             'APPLICATION.1.12': 'CA Service Management',
//             'CA_MGNT.1.1': 'Ticket list',
//             'CA_MGNT.1.2': 'Handle ticket',
//             'CA_MGNT.1.3': 'Contract management',
//             'CA_MGNT.1.4': 'Item list',
//             'CA_MGNT.1.5': 'Service list',
//             'CA_MGNT.1.6': 'Field list'
//         }
//     }
// };
